routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

 //Route::namespace('frontend')->group(function () {
 Route::get('/','LandingController@index')->name('landing');//});
 Route::get('/shapes/{slug}','LandingController@shapefullView')->name('shapefullview');

//Route::resource('login','LoginController');

Route::resource('admn/dashboard','DashboardController');
Route::resource('admn/products','ProductsController');
Route::resource('cart','frontend\CartController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::prefix('admin')->group(function () {
//dd('sssss');
	Route::middleware('auth')->group(function () {
		Route::get('toppings','ToppingController@index')->name('toppings.index');
		Route::get('toppings/edit/{id}','ToppingController@edit')->name('toppings.edit');
		Route::get('toppings/create','ToppingController@create')->name('toppings.create');
		Route::post('toppings/store','ToppingController@store')->name('toppings.store');
		Route::post('toppings/update','ToppingController@update')->name('toppings.update');
		Route::get('toppings/delete/{id}','ToppingController@delete')->name('toppings.delete');
		Route::get('pricing','PriceCalculatorController@index')->name('pricing.index');
		Route::get('pricing/create','PriceCalculatorController@create')->name('pricing.create');
		Route::post('pricing/store','PriceCalculatorController@store')->name('pricing.store');
		Route::get('pricing/edit/{id}','PriceCalculatorController@edit')->name('pricing.edit');
		Route::post('pricing/update','PriceCalculatorController@update')->name('pricing.update');
		Route::get('pricing/delete/{id}','PriceCalculatorController@delete')->name('pricing.delete');


	});
});

Route::prefix('Api/v1')->group(function () {
	Route::get('product.firms.get','ApiController@productFirms');
	Route::get('get.product.density','ApiController@getProductDensity')->name('get.product.density');
	//Route::get('product.items.get','ApiController@productItems');
});


//'PriceCalculatorController@index');

resources/views/includes/adminMenu.blade.php
 <!-- Left sidebar start -->
    <div class="vertical-nav">

        <!-- Collapse menu starts -->
        <button class="collapse-menu navButton">
            <i class="icon-menu2"></i>
        </button>
        <!-- Collapse menu ends -->

        <!-- Sidebar menu starts -->
        <ul class="menu clearfix">
            <li>
                <a href="{{url('admn/dashboard')}}">
                    <i class="icon-air-play"></i>
                    <span class="menu-item">Dashboard</span>
                </a>
            </li>
            <li>
                <a href="{{route('products.create')}}">
                    <i class="fa fa-shopping-cart"></i>
                    <span class="menu-item">Add Products</span>
                </a>
            </li>
            <li>
                <a href="{{route('products.index')}}">
                    <i class="fa fa-shopping-cart"></i>
                    <span class="menu-item">Our Products</span>
                </a>
            </li>
             <li>
                <a href="{{route('toppings.index')}}">
                    <i class="fa fa-shopping-cart"></i>
                    <span class="menu-item">Other Items</span>
                </a>
            </li>
            <li>
                <a href="{{route('pricing.index')}}">
                    <i class="fa fa-shopping-cart"></i>
                    <span class="menu-item">Pricing</span>
                </a>
            </li>
            <li>
                <a href="FoamCalculator.html">
                    <i class="fa fa-calculator"></i>
                    <span class="menu-item">Foam Calculator</span>
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-key"></i>
                    <span class="menu-item">Change Password</span>
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-shopping-cart"></i>
                    <span class="menu-item">Page Title</span>
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="icon-layers4"></i>
                    <span class="menu-item">Page Title</span>
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-shopping-cart"></i>
                    <span class="menu-item">Page Title</span>
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="icon-layers4"></i>
                    <span class="menu-item">Page Title</span>
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-shopping-cart"></i>
                    <span class="menu-item">Page Title</span>
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="icon-layers4"></i>
                    <span class="menu-item">Page Title</span>
                </a>
            </li>
        </ul>
        <!-- Sidebar menu ends -->
    </div>
    <!-- Left sidebar end -->

resources/views/includes/header.blade.php
 <!-- HEADER START -->

    <header class="header-main">
        <nav class="navbar navbar-expand-all fixed-top-head header-innerpage">
            <a class="navbar-brand" href="{{route('landing')}}">

                <img src="{{url('public/front/images/logo.png')}}" class="image" alt="logo">

            </a>
            <div class="ml-auto button-action ml-auto dropdown">
                <!-- <button class="btn-01 btn">Log In
                    <i class="fas fa-user"></i>
                </button> -->

                <button class="btn-user dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">
                    <i class="fas fa-user"></i>
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="#">
                        <i class="far fa-user"></i>Your Account</a>
                    <a class="dropdown-item" href="#">
                        <i class="fas fa-shopping-bag"></i>Your Orders </a>
                    <a class="dropdown-item" href="#">
                        <i class="fa fa-heart"></i>Shortlist</a>
                    <!-- <span class="para-1-dropdown">If you are new user</span> -->
                    <div class="btn-inline d-flex flex-column">
                        <button class="   btn-link" data-toggle="modal" data-target="#exampleModalCenter1">Register </button>
                        <button class="btn-01 btn dropdown-login" data-toggle="modal" data-target="#exampleModalCenter">Log In</button>
                    </div>
                </div>
            </div>
            <a href="cart.html" class="cart-mobile">
                <span class="item-count">2</span>
                <i class="fas fa-shopping-cart"></i>
            </a>

            <button onclick="openNav()" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <img src="{{url('public/front/images/bars.png')}}">
            </button>

        </nav>
    </header>